### PR TITLE
Memory Analysis

### PR DESCRIPTION
**Pull request by jposada202020**
## Context
After discussion regarding memory usage in some libraries I decide to take another look

This is an initial analysis of the memory footprint for the M0 boards.  Changes made
With the test code below, it was verified how much memory available was left. I did not build an `mpy` file. The analysis was made with the `py` file

## Changes and memory free increase
1. change to micropython `const` of some variables. ~0.1 Kb
2. Removal of CV class and descendants and replace by Tuples ~1Kb
3. Inclusion of gc.collect at the end of the init ~1Kb
4. Refactor of RwBits ~0.2 Kb for two replacements. Repalced by old bit masking and Bitwise logic

Expected memory free after the refactor removing the Register library ~+1.5kb

@tannewt and @ladyada just want to verify if the effort for 3.5-4Kb. If not this will help as a reference for the design guide.

Thanks

Tested on
```python
Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather RP2040 with rp2040
```

## Test Code

```python

# import dps310_simpletest

import board
import gc
print("memory initial", gc.mem_free())
import adafruit_dps310

i2c = board.I2C()  # uses board.SCL and board.SDA
# import dps310_simpletest

dps310 = adafruit_dps310.DPS310(i2c)

print("memory intermediate", gc.mem_free())
print("Temperature = %.2f *C" % dps310.temperature)
print("Pressure = %.2f hPa" % dps310.pressure)
print("memory Free = %.2f " % gc.mem_free())
print("")
```

### CODE REVIEW

**Comment by jposada202020** [comment]
@kmatch98 I know that memory guide more concentrated in the user side, however as the `expert` :) just FYI

**Comment by tannewt** [comment]
What is the starting size of the library? I'm not a huge fan of the CV class but I do like that it gives names and comments to the numeric values. Ideally they'd be Python enum classes. I'd rather not lose the usability those names give us.

**Comment by jposada202020** [comment]
Memory Initial = 211424 - 1933584 --> 17840
Final was around 196898 (or something) do not have that number copied

Regarding Enums, are those disable in M0s still in CircuitPython 7?

I prefer Robit, RWbits, are less affected by human errors, as they do not need masking and shifting calculations manually

**Comment by tannewt** [comment]
> Regarding Enums, are those disable in M0s still in CircuitPython 7?

I'm not sure.

> I prefer Robit, RWbits, are less affected by human errors, as they do not need masking and shifting calculations manually

I agree but I'm not sure what you are referring to.

**Comment by jposada202020** [comment]
I mean that is easy to extract bits from the Register using the Register library that do it yourself manually with `|` and `&` `>>` `<<` operations.
If needed I could work on lighter libraries and maybe put them in the community bundle or something, that way people will use and we do not need to support it. Thanks I will close this

**Comment by tannewt** [comment]
> If needed I could work on lighter libraries and maybe put them in the community bundle or something, that way people will use and we do not need to support it. Thanks I will close this

I don't think we need multiple libraries. Instead, complicated libraries should be split into multiple modules for different functionality.

One way to do the split here would be to simplify the core module and only allow configuration on a `configurable` subclass of it. Most of the configuration won't be used by folks.

**Comment by jposada202020** [comment]
I like very much the idea, I will think carefully, and make a second proposal, I will need to sleep on it, but yes I will work on this, I think this will help in other libraries that have the same problem, so this will be a good example, let me see what I came up with :) Thanks...

**Pull request closed without merging**
